version: "3"
services:
  hello:
    image: edtasixm11/k19:hello
    deploy:
      replicas: 3
    ports:
    - "80:80"
    networks:
    - mynet
  portainer:
    image: portainer/portainer
    ports:
    - "9000:9000"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
    - mynet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
    - "8080:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
    - mynet
networks:
  mynet:
