version: "3"
services:
  kserver:
    image: isx46420653/k19:kserver
    container_name: kserver.edt.org
    hostname: kserver.edt.org
    ports:
      - "88:88"
      - "464:464"
      - "749:749"
    networks:
      - mynet
  ldap:
    image: isx46420653/k19:ldapserver
    container_name: ldapserver.edt.org
    hostname: ldapserver.edt.org
    ports:
      - "389:389"
    networks:
      - mynet
  sshd:
    image: isx46420653/k19:sshdpl
    container_name: sshd.edt.org
    hostname: sshd.edt.org
    ports:
      - "22:22"
    networks:
      - mynet
networks:
  mynet:
